[package]
name = "scyrox_hid_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = "2.6"
notify-rust = "4"
serde = { version = "1", features = ["derive"] }
tao = "0.30"
toml = "0.8"
tray-icon = "0.19"
